POST https://curly-lamp-wp7w9q4jv4939qrv-3333.app.github.dev/users HTTP/1.1
Content-Type: application/json
Authorization: token xxx

{
  "name": "John Doe",
  "email": "john@example.com"
}
####

PUT  (https://curly-lamp-wp7w9q4jv4939qrv-3333.app.github.dev/users) HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe update",
  "email": "john@example.com"
}

####

DELETE  (https://curly-lamp-wp7w9q4jv4939qrv-3333.app.github.dev/users) HTTP/1.1


